#!/usr/bin/env php
<?php

use Cliver\Core\Console\Application;
use Cliver\Core\Console\ErrorHandler;
use Cliver\Core\Core\Bootstrap;

require __DIR__ . '/vendor/autoload.php';

$container = Bootstrap::init(__DIR__);

try {
    /** @var Application $app */
    $app = $container->get(Application::class);
    $status = $app->run($_SERVER['argv'])->value;
} catch (Throwable $e) {
    $status = ErrorHandler::handle($e)->value;
}

exit($status);
